:bug: Update jira instance connection column to use popover
konveyor/tackle2-ui pull request #1049
Opened 2023-06-16 21:26 UTC by sjd78

When a jira instance on the main jira configuration table has a connectivity issue, the connection column will show "Not connected". Clicking the text will now open a popover to display additional details about the state of the instance.  The popover replaces a standard modal box with similar information.

Fixes: #855

What it looked like before:
![image](https://github.com/konveyor/tackle2-ui/assets/3985964/1636600f-799c-491e-b3b7-6c0db7724edf)

What it looks like now:
![image](https://github.com/konveyor/tackle2-ui/assets/3985964/ce5422fb-0134-4a6f-a4b8-50969d7598c7)

2023-06-19 08:42 UTC, gildub commented
@sjd78, that sounds good, although during a previous conversation with @rromannissen the idea is to display errors from the Jira in code block (same for the tickets errors). 
Be aware the message can't be several lines long too.
So this needs to be validated by UXD.
Thansk

2023-06-19 13:42 UTC, gildub commented
@sjd78 , sounds good, I was concerned about the style change but I can see Ramon validation on the related issue.
Could you please rebase ?

2023-06-19 13:43 UTC, gildub requested changes
Looks good,
please use I18n for text as in initial code ?

2023-06-20 13:06 UTC, sjd78 commented
> Looks good, please use I18n for text as in initial code ?

I swapped the `"Connection"` text back to `t("terms.instance")` for the popover title.  I'll leave the description in the body above the code block since the popover design guidelines always include a header and descriptive text.  Having just the header with the code block text looks a bit awkward.

(rebased also)

2023-06-20 14:20 UTC, gildub reviewed
So we' re consistent please use i18n whenever there is user facing text.

2023-06-20 14:20 UTC, gildub commented on client/src/app/pages/external/jira/components/tracker-status.tsx
> +                  <Text>Jira instance {name} is not connected.</Text>
Can we use i18n text here ?

2023-06-21 12:49 UTC, ibolton336 approved these changes

2023-06-21 18:23 UTC, gildub approved these changes
LGTM, thanks !

2023-06-21 18:23 UTC, merged