Remove header expand icon bug
konveyor/tackle2-ui pull request #112
Opened 2022-04-18 23:43 UTC by ibolton336

https://issues.redhat.com/browse/TACKLE-434

2022-04-19 14:48 UTC, gildub approved these changes
Nice, I didn't think about CSS!

2022-04-19 14:49 UTC, gildub requested changes
Just need to fix the test.

2022-04-19 15:38 UTC, ibolton336 commented
@gildub Fixed - thx

2022-04-20 09:38 UTC, gildub approved these changes

2022-04-20 09:38 UTC, merged