wip
konveyor/tackle2-ui pull request #13
Opened 2022-02-24 22:29 UTC by ibolton336

2022-02-28 12:54 UTC, gildub reviewed
Looks good so far.

2022-03-01 14:14 UTC, gildub reviewed
Looks good.
Just need a cleanup.
There are some unused functions

2022-03-01 14:14 UTC, gildub commented on pkg/client/src/app/pages/proxies/proxy-form.tsx
> +  const onChangeIsHttpsIdentityRequired = () => {
Not used

2022-03-01 14:14 UTC, gildub commented on pkg/client/src/app/pages/proxies/proxy-form.tsx
> +  onCancel,
Not used

2022-03-01 17:40 UTC, gildub reviewed
When reloading the proxy page, after setting up one of the proxies, the switch button is showing deactivated.

The proxy page also needs to have the Textbox for the list of hosts to exclude from HTTP/HTTPS proxy.

2022-03-07 19:52 UTC, gildub requested changes
I wasn't able to save a proxy configuration.
Also the exclude list is not specific to https proxy but both

2022-03-07 19:52 UTC, gildub commented on pkg/client/src/app/pages/proxies/proxies.tsx
> +  // };
Do we need to keep this for later ? If yes then ignore my comment.

2022-03-07 19:52 UTC, gildub commented on pkg/client/src/app/pages/proxies/proxies.tsx
> +  // }, []);
same here ?

2022-03-07 19:52 UTC, gildub commented on pkg/client/src/app/pages/proxies/proxies-validation-schema.ts
> +    ),
This is already defined above.

2022-03-09 11:41 UTC, gildub reviewed
Code looks good.
Meanwhile when I test none of the Proxy switches are enabling.

2022-03-09 12:54 UTC, ibolton336 commented
> Code looks good. Meanwhile when I test none of the Proxy switches are enabling.

Do you have the latest images? @gildub

2022-03-11 16:56 UTC, gildub requested changes
Just tested against latest hub.
I can save fine but I can't disable after enabling either http or https proxy.
Also noted that the exclude list needs to be separate from proxies.

2022-03-14 14:17 UTC, gildub approved these changes
LGTM

2022-03-14 14:18 UTC, merged