:bug: Add application risk to assessment drawer
konveyor/tackle2-ui pull request #1488
Opened 2023-10-24 20:49 UTC by ibolton336

https://issues.redhat.com/browse/MTA-1504

2023-10-25 14:12 UTC, sjd78 requested changes

2023-10-25 14:12 UTC, sjd78 commented on client/src/app/pages/applications/components/application-detail-drawer/application-risk.tsx
> +  return <RiskLabel risk={application.risk || "unknown"} />;
With `risk` arriving on the application from hub, and only being shown from there, is any of the assessment fetching still needed?  Seems like the `ApplicationRisk` component may not be needed any longer.

2023-10-25 14:43 UTC, mturley reviewed
+1 to Scott's comment, otherwise LGTM

2023-10-26 19:54 UTC, sjd78 approved these changes
LGTM

2023-10-26 22:01 UTC, merged