Update business services table to use the ActionsColumn
konveyor/tackle2-ui pull request #1921
Opened 2024-05-23 09:26 UTC by mguetta1

Related to #1318

![image](https://github.com/konveyor/tackle2-ui/assets/60384172/c8a51e2e-171d-4637-865b-2f784b213f89)

2024-05-30 14:12 UTC, sjd78 reviewed
LGTM, I just want to check on the edit pencil icon in some other tables

2024-05-30 17:39 UTC, sjd78 approved these changes
LGTM

2024-05-31 13:09 UTC, sjd78 approved these changes

2024-05-31 13:11 UTC, sjd78 commented
@mguetta1 - I like the one with the edit pencil.  Which option do you want to use?

2024-05-31 13:46 UTC, rszwajko requested changes
@mguetta1  @ibolton336 
`AppTableActionButtons` is a wrapper that provides RBAC access check. Please provide some more context why we need to remove it.

2024-05-31 14:47 UTC, ibolton336 commented
> @mguetta1 @ibolton336 `AppTableActionButtons` is a wrapper that provides RBAC access check. Please provide some more context why we need to remove it.

The idea initially was to standardize on a common approach in the table now that this new table component was available. Modifying the AppTableActionButtons component to make use of the ActionsColumn may be a better approach. The use of PF Flex inside the AppTableActionButtons causes some inconsistent spacing when compared to the tables using ActionsColumn.

2024-05-31 15:17 UTC, sjd78 commented
> > @mguetta1 @ibolton336 `AppTableActionButtons` is a wrapper that provides RBAC access check. Please provide some more context why we need to remove it.
> 
> The idea initially was to standardize on a common approach in the table now that this new table component was available. Modifying the AppTableActionButtons component to make use of the ActionsColumn may be a better approach. The use of PF Flex inside the AppTableActionButtons causes some inconsistent spacing when compared to the tables using ActionsColumn.

Structurally I like the "new" style for the component layout.  However, with the different containing component, are we dropping some RBAC checks?  That could be ok so long as there is a new effort soon (i.e. in the release after 0.5) to refactor RBAC and apply it on all actions.  Humm, I may need to write up an issue to capture that work (and keycloak lib upgrades).

2024-06-02 07:14 UTC, mguetta1 commented
> @mguetta1 - I like the one with the edit pencil. Which option do you want to use?

This option

2024-06-02 07:19 UTC, mguetta1 commented
@rszwajko @ibolton336 @sjd78 
I don't think that there is any permission restrictions on controls. Anyway I added the `controlsWriteScopes` to the business service create button

2024-06-05 15:30 UTC, ibolton336 commented
> @rszwajko @ibolton336 @sjd78 I don't think that there is any permission restrictions on controls. Anyway I added the `controlsWriteScopes` to the business service create button [69ff6b2](https://github.com/konveyor/tackle2-ui/pull/1921/commits/69ff6b235eade30d3afd62f41c912c93724d049c)

I think it'd be worth trying to save the component for reuse as Radek mentioned. That way we don't need a new PR for each place we make these changes & can avoid maintenance headaches.

2024-06-06 10:41 UTC, mguetta1 commented
https://github.com/konveyor/tackle2-ui/assets/60384172/14457d94-b95c-4f36-a75e-a8d483077e15

2024-06-17 16:23 UTC, sjd78 requested changes
This looks good.  I'd just like to see the new component in a different folder.

2024-06-17 16:23 UTC, sjd78 commented on client/src/app/components/ControlTableActionButtons.tsx
This is probably better located in the folder `client/src/app/pages/controls` since the RBAC is setup for Controls.

2024-06-19 18:34 UTC, mguetta1 commented on client/src/app/components/ControlTableActionButtons.tsx
Done in https://github.com/konveyor/tackle2-ui/pull/1921/commits/730f1e020f23c25897643fabec5c6b62d5cfc942

2024-06-20 15:06 UTC, sjd78 approved these changes
LGTM

2024-06-20 22:01 UTC, merged