change icons in S_G table
konveyor/tackle2-ui pull request #2095
Opened 2024-09-15 10:52 UTC by MiriSafra

2024-09-15 19:40 UTC, mguetta1 requested changes
Thanks @MiriSafra for the PR. Please see my comments

2024-09-15 19:40 UTC, mguetta1 commented on client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
> +                        </TableRowContentWithControls> */}
@MiriSafra please remove comments

2024-09-15 19:40 UTC, mguetta1 commented on package-lock.json
No need to modify `package-lock.json` file

2024-09-16 08:55 UTC, mguetta1 approved these changes
LGTM

2024-09-17 21:27 UTC, mguetta1 commented
Closed and reopened the PR to update the description with UI tests PR

2024-09-26 14:09 UTC, rszwajko approved these changes

2024-09-26 14:25 UTC, rszwajko commented
@MiriSafra PR looks good - I've changed the title so that it would look more like previous work on this topic - see https://github.com/konveyor/tackle2-ui/pull/1923

2024-09-26 14:25 UTC, merged