:sparkles: Extend file upload to support Excel and ODS
konveyor/tackle2-ui pull request #2104
Opened 2024-09-22 07:02 UTC by Shevijacobson

adds support for uploading Excel (.xlsx, .xls) and OpenDocument Spreadsheet (.ods) formats in addition to CSV. It extends the file import functionality to support more common spreadsheet formats.

2024-10-29 19:17 UTC, rszwajko reviewed
Looks good! Please attach some screenshots presenting the change and error message.

2024-10-30 21:15 UTC, sjd78 commented
Does the hub support file uploads of those types?

What issue or ticket is this PR fixing?

2024-10-30 21:15 UTC, sjd78 reviewed
Does the hub support file uploads of those types?

What issue or ticket is this PR fixing?

2024-11-03 12:15 UTC, Shevijacobson commented
> Looks good! Please attach some screenshots presenting the change and error message.

I have added screenshots that present the changes and the error message as requested.

2024-11-03 13:16 UTC, Shevijacobson commented
> Does the hub support file uploads of those types?
> What issue or ticket is this PR fixing? Is it #2112?

The hub currently only supports CSV files, so I handle the file format conversion in the UI. Now, supported file types (like Excel and OpenDocument) are converted to CSV in the UI before being uploaded to the server. This approach avoids needing to add additional format support on the server.
Done in 9114f1e6c808bab70716c8acfafb473885a82ee6

The issue related is:  https://github.com/konveyor/enhancements/issues/121
Regarding issue #2112 - we could not reproduce it.

2024-11-06 10:39 UTC, rszwajko requested changes
IMHO we should search for an approach that doesn't require parsing and in-browser conversion to CSV or look for a different library.
The `xlsx` lib is a heavy one (claimed unpacked size of  7.5 MB) and has confusing browser/os support matrix (https://www.npmjs.com/package/xlsx)

2025-10-06 20:57 UTC, closed without merging

2025-10-06 20:57 UTC, sjd78 commented
Closing since doing file processing in browser is not optimal.  Best option is to allow upload of various file types and have the HUB endpoint handle accessing the data from the various file types.