:sparkles: Talya&Hadasah t table
konveyor/tackle2-ui pull request #2119
Opened 2024-10-08 09:34 UTC by TalyaNaima

changing the style of the edit & delete buttons in tags table (including the tags category)

2024-10-13 06:21 UTC, TalyaNaima commented
opening after running updated tests

2024-10-29 19:35 UTC, rszwajko requested changes
The change and PR look good - one minor fix needed  - remove extra table cell wrappers (see my comments below).

2024-10-29 19:35 UTC, rszwajko commented on client/src/app/pages/controls/tags/components/tag-table.tsx
>                <Td isActionCell>
We shouldn't wrap `ControlTableActionButtons` with  `<Td isActionCell>` as it already contains table cells inside.

2024-10-29 19:35 UTC, rszwajko commented on client/src/app/pages/controls/tags/tags.tsx
> +                        <Td>
No need to wrap with table cell.

2024-10-30 16:01 UTC, rszwajko approved these changes
LGTM!

2024-10-31 12:42 UTC, TalyaNaima commented
mguetta1, noticed that the rows of tags style has changed, 
the cause is that ControlTableActionButtons tags.ts has the right width only when wrapped with Td
![image (1)](https://github.com/user-attachments/assets/2d21fdc4-c557-4d65-b929-a6da743ef66b)
![image](https://github.com/user-attachments/assets/2772d7c0-f298-46fc-aa42-e3e745b31ca3)

2024-10-31 19:09 UTC, rszwajko commented
@mguetta1 @TalyaNaima  after https://github.com/konveyor/tackle2-ui/pull/2145 this will be more on the same line - the difference will be still there but I think it's a feature not a bug :)

2024-10-31 20:39 UTC, mguetta1 commented
Closed and reopened after updating the description with UI tests PR

2024-11-13 15:22 UTC, sjd78 commented
__Important__ -- This PR needs to co-merge with https://github.com/konveyor/tackle-ui-tests/pull/1237.  This cannot be done until a branch for release-0.6 / mta-7.2 is made in the [tackle-ui-tests](https://github.com/konveyor/tackle-ui-tests/branches).

2025-01-22 18:59 UTC, merged