:sparkles: Bulk download analysis reports
konveyor/tackle2-ui pull request #2142
Opened 2024-10-28 12:07 UTC by Shevijacobson

This PR introduces a new feature allowing users to download multiple analysis reports at once.
 A dedicated endpoint has been added in Hub to support bulk downloads, optimizing performance and reducing server load.

Related server-side changes can be found in [Tackle Hub PR #760](https://github.com/konveyor/tackle2-hub/pull/760).

related to: [MTA-394](https://issues.redhat.com/browse/MTA-394)

2024-10-28 15:01 UTC, jortel commented on client/src/app/api/rest.ts
> +    })
Is there a reasons this does not use the existing _List_ endpoint with a filter?
Example:
```
/tasks?filter=id:(1,2,3)
```

2024-10-28 15:02 UTC, jortel requested changes
See comment re: List with filter.

2024-10-30 22:30 UTC, sjd78 requested changes
Looks like a really nice base.  A few changes requested

2024-10-30 22:30 UTC, sjd78 commented on client/src/app/pages/applications/applications-table/applications-table.tsx
> +          : JSON.stringify(tasks, null, 2);
If the data is coming back in the requested "selectedFormat" why is it being formatted again?

2024-10-30 22:30 UTC, sjd78 commented on client/src/app/pages/applications/applications-table/applications-table.tsx
> +      console.error("Error fetching tasks:", error);
The user should be alerted to an error with at least a `pushNotification()`

2024-10-30 22:30 UTC, sjd78 commented on client/src/app/pages/applications/applications-table/applications-table.tsx
> +      </Modal>
The look of the modal needs to be updated.

Have a look at the "Show dropdown modal": https://www.patternfly.org/components/modal#with-dropdown

Put the modal's action buttons in the `actions` parameter so they render in the correct place with all the good spacing.


Put the yaml vs json selection in a basic drop down: https://www.patternfly.org/components/forms/form-select#basic

2025-04-22 17:47 UTC, sjd78 commented on client/src/app/pages/applications/applications-table/applications-table.tsx
> +          : JSON.stringify(tasks, null, 2);
Using different headers in the fetch can have the backend return json or yaml w/o the ui having to convert anything.

2025-04-22 17:50 UTC, sjd78 commented on client/src/app/pages/applications/applications-table/applications-table.tsx
> +      </Modal>
Changes look good.

2025-04-22 17:50 UTC, sjd78 approved these changes
LGTM

2025-04-22 20:06 UTC, merged