[Backport - v2.0.0] TACKLE-659: Ensure selected persona will get cleared on logout
konveyor/tackle2-ui pull request #289
Opened 2022-06-08 17:32 UTC by mturley

Backports #288 (for https://issues.redhat.com/browse/TACKLE-659)

2022-06-08 17:48 UTC, mturley commented
Note: do not merge until approved for 2.0.0 (under discussion on slack)

2022-06-08 18:19 UTC, jortel requested changes
HOLD pending issue triage.

2022-06-09 12:16 UTC, gildub approved these changes

2022-06-09 13:14 UTC, jortel approved these changes
LGTM
Issue triaged as blocker.

2022-06-09 13:15 UTC, merged