:bug: Alternate gold/red color for tag sources
konveyor/tackle2-ui pull request #745
Opened 2023-03-20 21:30 UTC by gildub

Resolves https://issues.redhat.com/browse/MTA-332

![image](https://user-images.githubusercontent.com/1901741/226470150-8c916380-b46b-443a-809c-e0aa92b3cbba.png)

2023-03-21 00:21 UTC, ibolton336 requested changes
Need to rethink this one together. Probably will need input from UXD and Ramon here.

2023-03-21 21:14 UTC, mturley commented
This might help :) https://github.com/migtools/lib-ui/pull/125

2023-03-28 07:24 UTC, gildub commented
@mturley, thanks and nice work with the migtools/lib-ui wrapper.
Good luck with the backend change in that regard.

2023-03-28 18:45 UTC, mturley commented on client/src/app/pages/applications/components/application-tags/application-tags.tsx
> -                        ?.sort((a, b) => a.name.localeCompare(b.name))
@gildub why remove the sorting here?

2023-03-28 18:46 UTC, mturley approved these changes
LGTM, left a question we can follow up on later.

2023-03-28 18:48 UTC, merged