:seedling: Convert stakeholder table to new table abstraction
konveyor/tackle2-ui pull request #828
Opened 2023-04-19 17:49 UTC by ibolton336

- useTableControls implementation for Stakeholders expandable form 
@mturley Nice work! We don't have to necessarily merge this as I know it is still under construction a bit. Just wanted to explore the changes. Works flawlessly. Only thing I did notice - we might need a way to make individual rows expandable. If I have a stakeholder with no groups assigned, I wonder if there is a way to make only that row not have an expandable icon displayed without shifting the columns/table rows.

2023-04-19 17:54 UTC, mturley commented
Nice!

Interesting, yeah, I think we can probably take advantage of the composable nature there and have some conditional expression on that cell where you only spread the `getCompoundExpandTdProps(...)` if that row should have it, else spread `getTdProps(...)`. Either that or we can add an `isCellExpandable` boolean to `getCompoundExpandTdProps` and have it exclude the necessary props when that's false.

2023-04-19 18:49 UTC, mturley submitted a review, later dismissed
LGTM! I'm totally fine merging this if you want, I already keep the migration waves / jira tables up to date whenever I change these hooks so it's not too much effort to manage one more. Within reason, the more tables we have using it the more confident we can be in the abstraction

2023-04-19 18:54 UTC, mturley commented
Actually @ibolton336 I approved too quickly, some minor things:
* On main, it looks like there is padding/margin around the contents of the expanded row content, and here the text is right up against the borders there
* For this single-expand use case I actually wanted to add support for automatically rendering that expand toggle cell as part of `<TableRowContentWithControls>`, but we can do that as a separate refactor after this if you want. Would just mean a little less code in the table.

2023-04-20 13:33 UTC, ibolton336 commented
> Actually @ibolton336 I approved too quickly, some minor things:
> 
> * On main, it looks like there is padding/margin around the contents of the expanded row content, and here the text is right up against the borders there

For some reason I am seeing an extra <td> in the expandable row that seems to be implicitly created by the legacy table.  

<img width="1264" alt="Screenshot 2023-04-20 at 9 26 13 AM" src="https://user-images.githubusercontent.com/11218376/233381142-e947f33f-b125-481a-b52b-794845cd0b7e.png">

2023-04-21 16:31 UTC, mturley requested changes
Looking good! A couple minor things

2023-04-21 16:31 UTC, mturley commented on client/src/app/pages/controls/stakeholders/stakeholders.tsx
> +                          {...getExpandTdProps({ item: stakeholder, rowIndex })}
Can we rename it to `getSingleExpandTdProps` to distinguish it from the compound expand version?

2023-04-21 16:31 UTC, mturley commented on client/src/app/pages/applications/components/application-form/application-form.tsx
> +            formGroupProps={{
Looks like the diff contains some stuff from another change?

2023-04-21 16:31 UTC, mturley commented on client/src/app/pages/controls/stakeholders/stakeholders.tsx
> +                        <Td />
Oh I see, this is to space it out so it is indented past the toggle. I guess that makes sense... hm, it does kinda suck that we have to remember to put this extra Td in though. I wonder if it's worth adding a new component for `<ExpandedContentRowWithControls>` or something that renders the Tr, the two Tds with the right props, and then passes children in.

Probably not worth it for now, I'll make a note to maybe mess with that later.

2023-04-21 16:31 UTC, mturley commented on client/src/app/shared/hooks/use-table-controls/useTableControlProps.ts
> +      expandId: "expandable-example",
These ids need to be unique for QE tests. We probably want to be able to pass in a custom id here, or maybe have it be something built-in like:
```ts
expandId: `expandable-row-${item.name}`
```

2023-04-21 20:17 UTC, ibolton336 commented
> Actually @ibolton336 I approved too quickly, some minor things:
> 
> * On main, it looks like there is padding/margin around the contents of the expanded row content, and here the text is right up against the borders there
> * For this single-expand use case I actually wanted to add support for automatically rendering that expand toggle cell as part of `<TableRowContentWithControls>`, but we can do that as a separate refactor after this if you want. Would just mean a little less code in the table.

Thanks @mturley For all the reviews. I think I hit all of the requested updates. Whenever you have time.

2023-04-25 00:14 UTC, mturley approved these changes

2023-04-25 00:14 UTC, merged

2023-06-06 19:05 UTC, sshveta commented
HI @mturley @ibolton336 .
In this PR the stakeholder table ID is changed to stakeholders-table .

All the other tables (like stakeholder Group , Business Service , applications page ) in MTA are using "table[aria-label='main-table']";.

Is it possible to keep the ID same and generic for all the tables ? 
That was enabling us to write common methods to delete all entities in page . 

Please let me know what you think .

2023-06-06 19:11 UTC, mturley commented
Hi @sshveta. 

I think we failed to properly communicate here, sorry about that. As established by #443 (which perhaps should not be closed), we do want to align on using `id` for QE tests where possible (or more specifically, avoiding having tests depend on `aria-label` which is user-facing text that is subject to change).

Perhaps we should use `id="main-table"` for each of the primary tables on the page, that is a decent idea. I'm curious about @ibolton336 's thoughts.

2023-06-12 13:11 UTC, ibolton336 commented
@mturley @sshveta Sorry for the oversight here. We can certainly move to a common id for these tables if that would be helpful.

2023-06-12 15:23 UTC, sshveta commented
Thanks @ibolton336 . Please let me know if I need to open a bug/issue for this .