:sparkles: jira initial new/edit instance
konveyor/tackle2-ui pull request #833
Opened 2023-04-22 11:29 UTC by gildub

https://github.com/konveyor/tackle2-ui/issues/588

2023-04-24 13:32 UTC, ibolton336 commented on client/src/app/FeatureFlags.ts
> +  migrationWaves: true,
Looks like this wasn't intentional.

2023-04-24 13:41 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +        isChecked={insecureCommunication}
Looking great, Gilles. I am wondering if this one is just left out of the form state due to lack of API support?

2023-04-24 13:44 UTC, ibolton336 commented on client/src/app/pages/external/jira/trackers.tsx
> +                    <ToolbarItem>setInstanceToUpdate
Minor cleanup here.

2023-04-25 14:43 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +        isRequired
Should this be required?

2023-04-25 14:46 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +  const [isKeyFileRejected, setIsKeyFileRejected] = useState(false);
Not used

2023-04-25 14:46 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +  const [isSettingsFileRejected, setIsSettingsFileRejected] = useState(false);
Not used

2023-04-25 14:52 UTC, ibolton336 requested changes
Looking good. A few small changes requested.

2023-04-25 14:52 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +            id="credentials-select"
Need to add: 

```
  maxHeight={DEFAULT_SELECT_MAX_HEIGHT}
  variant="typeahead"
```

This adds a default no results found when no identities are available. Also the max height helps with overflow in the case of a large number of options. Check the application-identity-form.tsx identity dropdown for an example.

2023-04-27 01:30 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +        renderInput={({ field: { value, name } }) => (
```suggestion
        renderInput={({ field: { value, name, onChange } }) => (
```

2023-04-27 01:30 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +              setValue("kind", selectionValue.value);
```suggestion
              onChange(selectionValue.value);
```

2023-04-27 01:51 UTC, ibolton336 commented on client/src/app/pages/external/jira/instance-form.tsx
> +      kind: instance?.kind || undefined,
```suggestion
      kind: instance?.kind,
```
Undefined will be assigned if kind does not exist on the instance object. That is wha optional chaining gets you.

2023-04-28 14:41 UTC, gildub commented on client/src/app/FeatureFlags.ts
> +  migrationWaves: true,
Ah yeah, just annoying to have to flip that one all the time.

2023-04-28 14:43 UTC, ibolton336 commented on client/src/app/FeatureFlags.ts
> +  migrationWaves: true,
Yeah I know what you mean. Can probably figure out a way for git to ignore changes to it locally.

2023-04-28 14:46 UTC, ibolton336 commented on client/src/app/FeatureFlags.ts
> +  migrationWaves: true,
``` git update-index --skip-worktree client/src/app/FeatureFlags.ts ```

2023-04-28 15:25 UTC, ibolton336 approved these changes

2023-04-28 15:33 UTC, merged