:bug: Fix edit migration wave
konveyor/tackle2-ui pull request #882
Opened 2023-05-10 22:28 UTC by ibolton336

2023-05-11 10:42 UTC, gildub requested changes
There still are issues. The date selected is not recorded to the same date, I'm not sure if it's because of my TZ.

2023-05-11 11:43 UTC, ibolton336 commented
> There still are issues. The date selected is not recorded to the same date, I'm not sure if it's because of my TZ.

Ah I think I see the issue. The validation for start date is checking against the current date for existing waves.

2023-05-11 13:59 UTC, gildub commented
The dates between table values and edit values don't match: 

![image](https://github.com/konveyor/tackle2-ui/assets/1901741/5a740b5e-097f-4dc6-ad71-e08c40466dc9)

![image](https://github.com/konveyor/tackle2-ui/assets/1901741/993002f3-84fd-4809-b38b-ffc2bf6d25b8)

2023-05-11 14:03 UTC, gildub requested changes
Same issue

2023-05-19 07:21 UTC, gildub reviewed
Looks good, just one minor comment.

2023-05-22 15:30 UTC, mturley reviewed
LGTM and works well. One note, which is maybe outside the scope of this fix but related to validation on these fields and is a 2-line fix.

2023-05-22 15:31 UTC, ibolton336 commented on client/src/app/pages/migration-waves/components/migration-wave-form.tsx
> +                renderInput={({ field: { value, name, onChange } }) => {
+1

2023-05-22 20:22 UTC, ibolton336 commented
Fixed, thanks @mturley

2023-05-22 20:40 UTC, mturley approved these changes
LGTM

2023-05-23 18:08 UTC, merged